routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/intro', 'HomeController@intro')->name('intro');

Route::get('admin', function (){
	if (Auth::user() == NULL) {
		return redirect('login');
	} else {
		if(Auth::user()->permission != 0) {
			return abort('404');
		}
	}
	return view('admin.dashboard');
	
})->name('adminDashboard');

Route::resource('admin/categories', 'CategoriesController');

Route::post('admin/categories/insert', 'CategoriesController@insert')->name('insertCategory');

Route::post('admin/categories/update/{id}', 'CategoriesController@update')->name('updateCategory');

Route::get('admin/categories/delete/{id}', 'CategoriesController@delete')->name('deleteCategory');

Route::resource('admin/products', 'ProductsController');

Route::post('admin/products/insert', 'ProductsController@insert')->name('insertProduct');

Route::post('admin/products/update/{id}', 'ProductsController@update')->name('updateProduct');

Route::get('admin/products/delete/{id}', 'ProductsController@delete')->name('deleteProduct');

Route::get('categoryProduct/{category_id}', 'ProductsController@showList')->name('showListProduct');

Route::resource('admin/orders', 'OrderController');

Route::post('admin/orders/insert', 'OrderController@insert')->name('insertOrder');

Route::post('admin/orders/update/{id}', 'OrderController@update')->name('updateOrder');

Route::get('admin/orders/delete/{id}', 'OrderController@delete')->name('deleteOrder');

Route::get('admin/printOrder/{id}', 'OrderController@printOrder')->name('printOrder');

Route::get('admin/statistics', 'StatisticsController@index')->name('indexStatistics');

Route::post('admin/statistics/getBy', 'StatisticsController@getBy')->name('getByStatistics');

Route::resource('admin/posts', 'PostController');

Route::post('admin/posts/insert', 'PostController@insert')->name('insertPost');

Route::post('admin/posts/update/{id}', 'PostController@update')->name('updatePost');

Route::get('admin/posts/delete/{id}', 'PostController@delete')->name('deletePost');

Route::get('categoryPost/{category_id}', 'PostController@showList')->name('showListPost');

Route::get('post/{id}', 'PostController@showSinglePost')->name('showSinglePost');

//// Clients

Route::get('products/{id}', 'ProductsController@show')->name('showProduct');

Route::get('cart', 'CartController@showCart')->name('showCart');

Route::get('addToCart', 'CartController@addToCart')->name('addToCart');

Route::post('updateCart', 'CartController@updateCart')->name('updateCart');

Route::get('emptyCart', 'CartController@emptyCart')->name('emptyCart');

Route::get('checkout', 'OrderController@showCheckout')->name('showCheckout');

Route::get('checkoutSuccess', 'OrderController@checkoutSuccess')->name('checkoutSuccess');

Route::get('search', 'ProductsController@search')->name('searchProduct');

Route::get('productOrder/{orderBy}/{order}', 'ProductsController@productOrder')->name('productOrder');

resources/views/admin/bill.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Hóa đơn</title>
	<link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
</head>
<body>
	<div class="container content-print-order" style="margin-top: 30px;">
		<div class="row">
			<div class="col-md-6">
				<h3>Tin Store</h3>
				<p>Địa chỉ: Tầng 18 tòa nhà ABC An Hòa Hà Đông, Hà Nội</p>
				<p>Hotline: 0123456789</p>
				<p>Email: TinStore&#64;gmail.com</p>
				<p>Website: tinstore.com</p>
			</div>
			<div class="col-md-6">
				<h3>HÓA ĐƠN BÁN HÀNG</h3>
				@if(!empty($order))
				<p>Mã đơn hàng: MĐH{{ $order->id }}</p>
				<p>Khách hàng: {{ $order->name }}</p>
				<p>Số điện thoại: {{ $order->phone }}</p>
				<p>Địa chỉ: {{ $order->address }}</p>
				<p>Ghi chú: {{ $order->description }}</p>
				@endif
			</div>
		</div>

		<div class="row">
			<table class="table table-inverse table-bordered text-center">
				<thead>
					<tr>
						<th>STT</th>
						<th>Mặt hàng</th>
						<th>Số lượng</th>
						<th>Đơn Giá</th>
						<th>Thành tiền</th>
					</tr>
				</thead>
				<tbody>
					<?php $stt = 1; ?> 
					@if(!empty($orderItems))
					@foreach($orderItems as $key => $item)
					<tr>
						<td>{{ $stt++ }}</td>
						<td>{{ $item->name }}</td>
						<td>{{ $item->quantity }}</td>
						<td>{{ number_format( $item->price, 0, ',', '.' ) }}đ</td>
						<td>{{ number_format( $item->price * $item->quantity, 0, ',', '.' ) }}đ</td>
					</tr>
					@endforeach
					@endif
				</tbody>
			</table>

		</div>

		<div class="row" style="margin-top: 30px;">
			<div class="col-md-4">
				<p class="text-center">Người lập hóa đơn</p>
			</div>
			<div class="col-md-8 text-center">
				<p class="">Tổng cộng: {{ number_format( $order->total, 0, ',', '.' ) }}đ</p>
				<p class="">Ngày ... Tháng ... Năm ...</p>
			</div>
		</div>
	</div>
</body>
</html>

resources/views/admin/category.blade.php
@extends('admin.layouts.master')
@section('title')
Category - List
@endsection

@section('content')
<h1><center>Danh sách</center></h1>
<div class="container">
    
    @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif

    @if(session()->has('error'))
        <div class="alert alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

	<table id="categories_table" class="table table-striped table-bordered text-center" style="width:100%;">
        <thead>
            <tr>
                <th>ID</th>
                <th>Danh mục</th>
                <th>Danh mục cha</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tbody>
        	@foreach( $categories as $cat)
        	<tr>
                <td>{{ $cat->id }}</td>
                <td>{{ $cat->name }}</td>
                <td>
                	@foreach($categories as $innerCat)
                	@if($cat->parent_id == $innerCat->id)
                	{{ $innerCat->name }}
                	@endif
                	@endforeach
                </td>
                <td>{{ $cat->created_at }}</td>
                <td>{{ $cat->updated_at }}</td>
                <td>
                    @if($cat->id > 2)
                	<a href="{{ route('categories.show', ['id' => $cat->id]) }}">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                	<a href="{{ route('deleteCategory', ['id' => $cat->id]) }}" class="confirm">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                    @endif
                </td>
            </tr>
            @endforeach
    	</tbody>
    	<tfoot>
            <tr>
                <th>ID</th>
                <th>Danh mục</th>
                <th>Danh mục cha</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </tfoot>
	</table>
	<script type="text/javascript">
		$(document).ready( function () {
		    $('#categories_table').DataTable();
		} );
	</script>
</div>

<br>
<hr>
<br>

<h1><center>Thêm danh mục</center></h1>
<div class="container">
	<form action="/admin/categories/insert" method="post">
		<div class="form-group row">
			<label for="inputEmail3" class="col-sm-2 form-control-label">Tên danh mục</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" id="inputEmail3" placeholder="tên danh mục" name="name">
			</div>
		</div>
		<div class="form-group row">
			<label for="inputPassword3" class="col-sm-2 form-control-label">Danh mục cha</label>
			<div class="col-sm-10">
				<select class="form-control" name="parent_id">
					<option value="0">--- Chọn ---</option>
					@foreach( $categories as $cat)
					<option value="{{ $cat->id }}">{{ $cat->name }}</option>
					@endforeach
				</select>
			</div>
		</div>
		<div class="form-group row">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-primary">Thêm</button>
			</div>
		</div>

		@csrf
	</form>
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.master')
@section('title')
Dashboard
@endsection

@section('content')
<div class="container">
	<p><center><i>Dashboard</i></center></p>
</div>
@endsection

resources/views/admin/order.blade.php
@extends('admin.layouts.master')
@section('title')
Order - List
@endsection

@section('content')
<?php $status = ['Đang chờ', 'Đã thanh toán', 'Đã hủy']; ?>
@if(isset($orders))
<div class="container" style="margin-top: 30px;">

    @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif

    @if(session()->has('error'))
        <div class="alert alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif
    
    
	<table id="orders_table" class="table table-striped table-bordered text-center" style="width:100%;">
        <thead>
            <tr>
                <th>Mã đơn hàng</th>
                <th>User</th>
                <th>Họ tên người nhận</th>
                <th>Địa chỉ</th>
                <th>Trạng thái</th>
                <th>Tổng số tiền</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tbody>
            @if(!empty($orders))
        	@foreach( $orders as $order)
        	<tr>
                <td>MĐH{{ $order->id }}</td>
                <td>
                    @if($order->user_id == 0)
                    {{ 'Mua tại cửa hàng' }}
                    @endif

                    @if($order->user_id != 0)
                        @foreach($users as $user)
                            @if($user->id == $order->user_id)
                                {{ $user->name }}
                            @endif
                        @endforeach
                    @endif
                </td>
                <td>{{ $order->name }}</td>
                <td>{{ $order->address }}</td>
                <td>{{ $status[$order->status] }}</td>
                <td>{{ number_format( $order->total, 0, ',', '.' ) }}đ</td>
                <td>{{ $order->created_at }}</td>
                <td>{{ $order->updated_at }}</td>
                <td>
                	<a href="{{ route('orders.show', ['id' => $order->id]) }}">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                	<a href="{{ route('deleteOrder', ['id' => $order->id]) }}" class="confirm">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>   
                    </a>
                    <a href="{{ route('printOrder', ['id' => $order->id]) }}" target="_blank">
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
            @endforeach
            @endif
    	</tbody>
    	<tfoot>
            <tr>
                <th>Mã đơn hàng</th>
                <th>User</th>
                <th>Họ tên người nhận</th>
                <th>Địa chỉ</th>
                <th>Trạng thái</th>
                <th>Tổng số tiền</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </tfoot>
	</table>
	<script type="text/javascript">
		$(document).ready( function () {
		    $('#orders_table').DataTable();
		} );
	</script>

</div>
@endif

@if(isset($update_order))
<br>
<br>
<h1><center>Hóa đơn MHĐ{{ $update_order->id }}</center></h1>
<div class="container">
    <form action="{{ route('orders.store') }}" method="post">
        <div class="form-group row">
            <label for="address" class="col-sm-2 form-control-label">Địa chỉ</label>
            <div class="col-sm-10">
                <span class="form-control">{{ $update_order->address }}</span>
            </div>
        </div>
        <div class="form-group row">
            <label for="user_id" class="col-sm-2 form-control-label">Khách hàng</label>
            <div class="col-sm-10">
                <span class="form-control">
                    @foreach( $users as $user)
                    @if($user->id == $update_order->user_id)
                        {{ $user->name }}
                    @endif
                    @endforeach
                </span>
            </div>
        </div>

        <div class="form-group row">
            <label for="status" class="col-sm-2 form-control-label">Trạng thái</label>
            <div class="col-sm-10">
                <select class="form-control" name="status" id="status">
                    <option value="0" @if($update_order->status == 0) {{ 'selected' }} @endif>Đang chờ</option>
                    <option value="1" @if($update_order->status == 1) {{ 'selected' }} @endif>Đã thanh toán</option>
                    <option value="2" @if($update_order->status == 2) {{ 'selected' }} @endif>Hủy</option>
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="description" class="col-sm-2 form-control-label">Ghi chú</label>
            <div class="col-sm-10">
                <textarea id="description" class="form-control" name="description" placeholder="Ghi chú">{{ $update_order->description }}</textarea>
            </div>
            <input type="hidden" name="id" value="{{ $update_order->id }}">
        </div>

        <div class="form-group row">
            <label class="col-sm-2 form-control-label">Tổng tiền</label>
            <div class="col-sm-10">
                <span class="form-control">{{ number_format( $update_order->total, 0, ',', '.' ) }}đ</span>
            </div>

        </div>

        <div class="form-group row">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Sửa</button>
            </div>
        </div>

        @csrf
    </form>
</div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-inverse">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Mặt hàng</th>
                            <th>Số lượng</th>
                            <th>Đơn Giá</th>
                            <th>Thành tiền</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $stt = 1; ?> 
                        @if(!empty($orderItems))
                        @foreach($orderItems as $key => $item)
                        <tr>
                            <td>{{ $stt++ }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td>{{ number_format( $item->price, 0, ',', '.' ) }}đ</td>
                            <td>{{ number_format( $item->price * $item->quantity, 0, ',', '.' ) }}đ</td>
                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
@endif
@endsection

resources/views/admin/post.blade.php
@extends('admin.layouts.master')
@section('title')
Post - List
@endsection

@section('content')
@if(isset($posts))
<div class="container" style="margin-top: 30px;">

    @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif

    @if(session()->has('error'))
        <div class="alert alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif
    
    
	<table id="post_table" class="table table-striped table-bordered text-center" style="width:100%;">
        <thead>
            <tr>
                <th>ID</th>
                <th>title</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tbody>
           @foreach($posts as $post)
           <tr>
               <td>{{ $post->id }}</td>
               <td>{{ $post->title }}</td>
               <td>{{ $post->created_at }}</td>
               <td>{{ $post->updated_at }}</td>
               <td>
                    <a href="{{ route('posts.edit', ['id' => $post->id]) }}">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a href="{{ route('deletePost', ['id' => $post->id]) }}" class="confirm">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                </td>
           </tr>
           @endforeach
    	<tfoot>
            <tr>
                <th>ID</th>
                <th>title</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </tfoot>
	</table>
	<script type="text/javascript">
		$(document).ready( function () {
		    $('#post_table').DataTable();
		} );
	</script>

</div>
@endif

<h1><center>Thêm bài viết</center></h1>
<div class="container">
    <form action="/admin/posts/insert" method="post">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 form-control-label">Tiêu đề</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputEmail3" placeholder="Tên sản phẩm" name="title">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 form-control-label">Danh mục</label>
            <div class="col-sm-10">
                <select class="form-control" name="category_id">
                    <option value="0">Chọn danh mục</option>
                    @foreach( $categories as $cat)
                    <option value="{{ $cat->id }}">{{ $cat->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="short_description" class="col-sm-2 form-control-label">Mô tả ngắn</label>
            <div class="col-sm-10">
                <textarea rows="5" name="short_description" class="form-control" placeholder="Mô tả ngắn"  id="short_content"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="description" class="col-sm-2 form-control-label">Nội dung</label>
            <div class="col-sm-10">
                <textarea rows="10" name="content" class="form-control" placeholder="Mô tả"  id="content"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Thêm</button>
            </div>
        </div>
        @csrf
    </form>
</div>
@endsection

resources/views/admin/product.blade.php
@extends('admin.layouts.master')
@section('title')
Product - List
@endsection

@section('content')

<div class="container" style="margin-top: 30px;">

    @if(session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif

    @if(session()->has('error'))
        <div class="alert alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

	<table id="products_table" class=" table-striped table-bordered text-center" style="width:100%;">
        <thead>
            <tr>
                <th>ID</th>
                <th>Sản phẩm</th>
                <th>Danh mục</th>
                <th>Ảnh</th>
                <th>Giá</th>
                <th>Số lượng</th>
                <th>Giảm giá</th>
                <th>Giới tính</th>
                <th>Lượt xem</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </thead>
        <tbody>
        	@foreach( $products as $product)
        	<tr>
                <td>{{ $product->id }}</td>
                <td>{{ $product->name }}</td>
                <td>
                    @foreach( $categories as $cat)
                        @if($product->category_id == $cat->id)
                            {{ $cat->name }}
                        @endif
                    @endforeach
                </td>
                <td><img src="{{ asset($product->image) }}" style="max-width: 150px;"></td>
                <td>{{ $product->price }}</td>
                <td>{{ $product->quantity }}</td>
                <td>{{ $product->sale }}%</td>
                <td>{{ $product->sex == 1 ? 'nam' : 'nữ' }}</td>
                <td>{{ $product->view }}</td>
                <td>{{ $product->created_at }}</td>
                <td>{{ $product->updated_at }}</td>
                <td>
                	<a href="{{ route('products.edit', ['id' => $product->id]) }}">
                     <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                	<a href="{{ route('deleteProduct', ['id' => $product->id]) }}" class="confirm">
                     <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
            @endforeach
    	</tbody>
    	<tfoot>
            <tr>
                <th>ID</th>
                <th>Sản phẩm</th>
                <th>Danh mục</th>
                <th>Ảnh</th>
                <th>Giá</th>
                <th>Số lượng</th>
                <th>Giảm giá</th>
                <th>Giới tính</th>
                <th>Lượt xem</th>
                <th>Thời gian tạo</th>
                <th>Cập nhật lần cuối</th>
                <th>Thao tác</th>
            </tr>
        </tfoot>
	</table>
	<script type="text/javascript">
		$(document).ready( function () {
		    $('#products_table').DataTable();
		} );
	</script>
</div>

<br>
<hr>
<br>

<h1><center>Thêm sản phẩm</center></h1>
<div class="container">
    <form action="/admin/products/insert" method="post" enctype="multipart/form-data">
        <div class="form-group row">
            <label for="inputEmail3" class="col-sm-2 form-control-label">Tên sản phẩm</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="inputEmail3" placeholder="Tên sản phẩm" name="name">
            </div>
        </div>
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 form-control-label">Danh mục</label>
            <div class="col-sm-10">
                <select class="form-control" name="category_id">
                    <option value="0">Chọn danh mục</option>
                    @foreach( $categories as $cat)
                    <option value="{{ $cat->id }}">{{ $cat->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="quantity" class="col-sm-2 form-control-label">Số lượng</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="quantity" placeholder="Số lượng" name="quantity">
            </div>
        </div>
        <div class="form-group row">
            <label for="price" class="col-sm-2 form-control-label">Giá</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="price" placeholder="Giá" name="price">
            </div>
        </div>
        <div class="form-group row">
            <label for="sale" class="col-sm-2 form-control-label">Giảm giá</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="sale" placeholder="Giảm giá" name="sale">
            </div>
        </div>
        <div class="form-group row">
            <label for="sex" class="col-sm-2 form-control-label">Giới tính</label>
            <div class="col-sm-10">
                <select class="form-control" name="sex">
                    <option value="1">Nam</option>
                    <option value="0">Nữ</option>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="short_description" class="col-sm-2 form-control-label">Mô tả ngắn</label>
            <div class="col-sm-10">
                <textarea name="short_description" class="form-control" placeholder="Mô tả ngắn"  id="short_description" required="required"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="description" class="col-sm-2 form-control-label">Mô tả</label>
            <div class="col-sm-10">
                <textarea name="description" class="form-control" placeholder="Mô tả"  id="description" required="required"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="image" class="col-sm-2 form-control-label">Ảnh</label>
            <div class="col-sm-10">
                <input type="file" class="form-control-file" name="image" id="image" aria-describedby="fileHelp" required="required">
                <small id="fileHelp" class="form-text text-muted">Please upload a valid image file. Size of image should not be more than 2MB.</small>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Thêm</button>
            </div>
        </div>
        @csrf
    </form>
</div>
@endsection

resources/views/admin/statics.blade.php
@extends('admin.layouts.master')
@section('title')
Statics
@endsection

@section('content')
    <div class="container" style="margin-top: 40px;">
        <div class="row" style="margin-bottom: 25px;">
            <div class="col-md-12">
                <h3>Xu hướng</h3>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="xu_huong">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td>Sản phẩm nhiều lượt xem nhất: </td>
                                <td>
                                    @if(isset($data['productView']))
                                    <a href="{{ route('products.edit', ['id' => $data['productView']->id]) }}">{{ $data['productView']->name }}</a>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td>Sản phẩm bán chạy nhất: </td>
                                <td>
                                    @if(isset($data['productBestSell']))
                                    <a href="{{ route('products.edit', ['id' => $data['productBestSell']['id']]) }}">{{ $data['productBestSell']['name'] }}</a>
                                    @endif
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row" style="margin-bottom: 25px;">
            <div class="col-md-12">
                <h3>Thống kê đơn hàng</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="Thu nhập">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <td>Đơn hàng lớn nhất: </td>
                                <td>
                                    @if(isset($data['orderMax']))
                                    <a href="{{ route('orders.show', ['id' => $data['orderMax']->id]) }}">MĐH{{ $data['orderMax']->id }}</a>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td>Đơn hàng nhỏ nhất: </td>
                                <td>
                                    @if(isset($data['orderMin']))
                                    <a href="{{ route('orders.show', ['id' => $data['orderMin']->id]) }}">MĐH{{ $data['orderMin']->id }}</a>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td>Tổng số đơn hàng </td>
                                <td>{{ $data['totalCountOrder'] }}</td>
                            </tr>
                            <tr>
                                <td>Tổng số tiền các đơn hàng </td>
                                <td>{{ number_format($data['totalPriceOrder'], 0, ',', '.') }}đ</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <h3>Xem thống kê</h3>
                <form action="{{ route('getByStatistics') }}" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Tháng</label>
                        <div class="col-sm-10">
                            <input type="number" min="1" max="12" class="form-control" name="thang">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Quý</label>
                        <div class="col-sm-10">
                            <input type="number" min="1" max="4" class="form-control" name="quy">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Năm</label>
                        <div class="col-sm-10">
                            <input type="number" min="1990" max="2099" class="form-control" name="nam">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 form-control-label">Thống kê theo</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="by">
                                <option value="t">Tháng</option>
                                <option value="q">Quý</option>
                                <option value="n">Năm</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">Xem</button>
                        </div>
                    </div>

                    @csrf
                </form>
            </div>
        </div>
    </div>
@endsection