routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/intro', 'HomeController@intro')->name('intro');

Route::get('admin', function (){
	if (Auth::user() == NULL) {
		return redirect('login');
	} else {
		if(Auth::user()->permission != 0) {
			return abort('404');
		}
	}
	return view('admin.dashboard');
	
})->name('adminDashboard');

Route::resource('admin/categories', 'CategoriesController');

Route::post('admin/categories/insert', 'CategoriesController@insert')->name('insertCategory');

Route::post('admin/categories/update/{id}', 'CategoriesController@update')->name('updateCategory');

Route::get('admin/categories/delete/{id}', 'CategoriesController@delete')->name('deleteCategory');

Route::resource('admin/products', 'ProductsController');

Route::post('admin/products/insert', 'ProductsController@insert')->name('insertProduct');

Route::post('admin/products/update/{id}', 'ProductsController@update')->name('updateProduct');

Route::get('admin/products/delete/{id}', 'ProductsController@delete')->name('deleteProduct');

Route::get('categoryProduct/{category_id}', 'ProductsController@showList')->name('showListProduct');

Route::resource('admin/orders', 'OrderController');

Route::post('admin/orders/insert', 'OrderController@insert')->name('insertOrder');

Route::post('admin/orders/update/{id}', 'OrderController@update')->name('updateOrder');

Route::get('admin/orders/delete/{id}', 'OrderController@delete')->name('deleteOrder');

Route::get('admin/printOrder/{id}', 'OrderController@printOrder')->name('printOrder');

Route::get('admin/statistics', 'StatisticsController@index')->name('indexStatistics');

Route::post('admin/statistics/getBy', 'StatisticsController@getBy')->name('getByStatistics');

Route::resource('admin/posts', 'PostController');

Route::post('admin/posts/insert', 'PostController@insert')->name('insertPost');

Route::post('admin/posts/update/{id}', 'PostController@update')->name('updatePost');

Route::get('admin/posts/delete/{id}', 'PostController@delete')->name('deletePost');

Route::get('categoryPost/{category_id}', 'PostController@showList')->name('showListPost');

Route::get('post/{id}', 'PostController@showSinglePost')->name('showSinglePost');

//// Clients

Route::get('products/{id}', 'ProductsController@show')->name('showProduct');

Route::get('cart', 'CartController@showCart')->name('showCart');

Route::get('addToCart', 'CartController@addToCart')->name('addToCart');

Route::post('updateCart', 'CartController@updateCart')->name('updateCart');

Route::get('emptyCart', 'CartController@emptyCart')->name('emptyCart');

Route::get('checkout', 'OrderController@showCheckout')->name('showCheckout');

Route::get('checkoutSuccess', 'OrderController@checkoutSuccess')->name('checkoutSuccess');

Route::get('search', 'ProductsController@search')->name('searchProduct');

Route::get('productOrder/{orderBy}/{order}', 'ProductsController@productOrder')->name('productOrder');

resources/views/admin/layouts/footer.blade.php
	<div class="container-fuid">
		<p><center><i>Copyright by DevTeam 2018</i></center></p>
	</div>
	</body>
</html>

resources/views/admin/layouts/header.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>@yield('title')</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/custom.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('font-awesome-4.7.0/css/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('DataTables_for_bootstrap4/datatables.min.css') }}">
    <script src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript" src="{{ asset('DataTables_for_bootstrap4/datatables.min.js') }}"></script>
    <script src="{{ asset('js/custom.js') }}"></script>
  </head>
  <body>
    

resources/views/admin/layouts/master.blade.php
@include('admin.layouts.header')
@include('admin.layouts.navbar')
@yield('content')
@include('admin.layouts.footer')

resources/views/admin/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href=" {{ route('adminDashboard') }} ">Clothes Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href=" {{ route('categories.index') }} ">Danh mục</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {{ route('products.index') }} ">Sản phẩm</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {{ route('orders.index') }} ">Đơn hàng</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {{ route('posts.index') }} ">Tin tức</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {{ route('indexStatistics') }} ">Thống kê</a>
      </li>
      <li class="nav-item dropdown">
            @auth
              <a class="nav-link dropdown-toggle username" href="#" id="logged" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Xin chào {{ \Auth::user()->name }}
              </a>
              <div class="dropdown-menu" aria-labelledby="logged">
                <a class="dropdown-item" href="{{ route('logout') }}"
                                 onclick="event.preventDefault();
                                               document.getElementById('logout-form').submit();">
                                  {{ __('Đăng xuất') }}
                              </a>

                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                  @csrf
                              </form>
              </div>
              
                    @else
            <a class="nav-link dropdown-toggle" href="#" id="login-register" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Đăng nhập/Đăng ký
            </a>
            <div class="dropdown-menu" aria-labelledby="login-register">
              <a class="dropdown-item" href="{{ route('login') }}">Đăng nhập</a>
              <a class="dropdown-item" href="{{ route('register') }}">Đăng ký</a>
            </div>
                    @endauth
          </li>
    </ul>
  </div>
</nav>